---
abstract: 'Adds a release test to ensure that all modules have the same $VERSION'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101310'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ConsistentVersionTest
recommends: {}
requires:
  Test::ConsistentVersion: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-ConsistentVersionTest
  repository: http://hg.urth.org/hg/Dist-Zilla-Plugin-ConsistentVersionTest
version: 0.01
